CREATE TABLE `FUSER` (
	`ID` INT(255) UNSIGNED NOT NULL,
	`Name` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `LOCATION` (
	`PLACE` INT(255) UNSIGNED NOT NULL,
	`XAXIS` INT(255) NULL DEFAULT NULL,
	`YAXIS` INT(255) NULL DEFAULT NULL,
	`ZAXIS` INT(255) NULL DEFAULT NULL,
	PRIMARY KEY (`PLACE`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;



CREATE TABLE `REVIEW` (
	`USERID` INT(225) UNSIGNED NULL DEFAULT NULL,
	`PLACEID` INT(225) UNSIGNED NULL DEFAULT NULL,
	`TEXT` VARCHAR(1000) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	INDEX `FK_REVIEW_LOCATION` (`PLACEID`) USING BTREE,
	INDEX `FK_REVIEW_USER` (`USERID`) USING BTREE,
	CONSTRAINT `FK_REVIEW_LOCATION` FOREIGN KEY (`PLACEID`) REFERENCES `user_rate`.`LOCATION` (`PLACE`) ON UPDATE RESTRICT ON DELETE NO ACTION,
	CONSTRAINT `FK_REVIEW_USER` FOREIGN KEY (`USERID`) REFERENCES `user_rate`.`USER` (`ID`) ON UPDATE RESTRICT ON DELETE NO ACTION
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
